"""Immutable workbook content for prescribed ARAL activities.

The activity key, rather than a teacher-editable label, identifies the
workbook interaction everywhere it is used.
"""

from copy import deepcopy


LESSON_16_IMAGE_PATHS = {
    'gumamela': 'pabasa_app/images/lesson_16/gumamela.png',
    'banga': 'pabasa_app/images/lesson_16/banga.png',
    'gusali': 'pabasa_app/images/lesson_16/gusali.png',
    'ngiti': 'pabasa_app/images/lesson_16/ngiti.png',
    'gata': 'pabasa_app/images/lesson_16/gata.png',
    # These filenames are intentional placeholders.  The Lesson 16 Gawain 3
    # workbook images can be added later without changing its activity data.
    'sanga': 'pabasa_app/images/lesson_16/sanga.png',
    'goma': 'pabasa_app/images/lesson_16/goma.png',
    'bunga': 'pabasa_app/images/lesson_16/bunga.png',
    'panga': 'pabasa_app/images/lesson_16/panga.png',
    'gamot': 'pabasa_app/images/lesson_16/gamot.png',
}


PRESCRIBED_ACTIVITIES = {
    'lesson7-gawain4b': {
        'activity_key': 'lesson7-gawain4b', 'session_key': 'session-3', 'session_number': 3,
        'lesson_number': 7, 'gawain_number': '4B', 'title': 'GAWAIN 4B: Letrang Ii at Oo',
        'instruction': 'I-type ang i kung ang larawan ay nagsisimula sa titik /i/. I-type ang o kung ang larawan ay nagsisimula sa titik /o/.',
        'interaction': 'oral_then_written', 'items': [
            {'word': 'orasan', 'answer': 'o', 'image_path': 'pabasa_app/images/letrang_o_4b/orasan.png'},
            {'word': 'ilog', 'answer': 'i', 'image_path': 'pabasa_app/images/letrang_o_4b/ilog.png'},
            {'word': 'ibon', 'answer': 'i', 'image_path': 'pabasa_app/images/letrang_o_4b/ibon.png'},
            {'word': 'okra', 'answer': 'o', 'image_path': 'pabasa_app/images/letrang_o_4b/okra.png'},
            {'word': 'oso', 'answer': 'o', 'image_path': 'pabasa_app/images/letrang_o_4b/oso.png'},
            {'word': 'ilaw', 'answer': 'i', 'image_path': 'pabasa_app/images/letrang_o_4b/ilaw.png'},
        ],
    },
    'lesson-26-gawain-1': {
        'activity_key': 'lesson-26-gawain-1', 'session_number': 10, 'lesson_number': 26,
        'gawain_number': 1, 'title': 'Word Search', 'title_fil': 'Hanap-Salita',
        'instruction': 'Read the word on the left, then find it in the grid. Words may be placed horizontally, vertically, or diagonally.',
        'interaction': 'word_search', 'total_items': 5,
        'grid': [['c','a','t','h'], ['t','o','p','m'], ['a','t','a','a'], ['x','p','a','t'], ['h','a','t','f']],
        'words': ['mat', 'top', 'tax', 'hat', 'cat'],
        'items': [{'word': word, 'image_path': 'pabasa_app/images/sound_detective/detective_bg.png'} for word in ['mat', 'top', 'tax', 'hat', 'cat']],
    },
    'lesson-26-gawain-2': {
        'activity_key': 'lesson-26-gawain-2', 'session_number': 10, 'lesson_number': 26,
        'gawain_number': 2, 'title': 'Fill in the Blanks',
        'instruction': 'Fill in the blanks with the correct words from the list.',
        'interaction': 'fill_blank_sentence', 'total_items': 4,
        'choices': ['hat', 'cat', 'rat', 'mat'],
        'items': [
            {'id': 'sentence-1', 'parts': ['The furry ', ' on the warm ', '.'], 'answers': ['cat', 'mat'], 'image_path': 'pabasa_app/images/sound_detective/detective_bg.png'},
            {'id': 'sentence-2', 'parts': ['The ', ' fell off her head.'], 'answers': ['hat'], 'image_path': 'pabasa_app/images/sound_detective/detective_bg.png'},
            {'id': 'sentence-3', 'parts': ['The ', ' ate the ', '.'], 'answers': ['rat', 'hat'], 'image_path': 'pabasa_app/images/sound_detective/detective_bg.png'},
            {'id': 'sentence-4', 'parts': ['The ', ' was placed on the top of the shelf.'], 'answers': ['hat'], 'image_path': 'pabasa_app/images/sound_detective/detective_bg.png'},
        ],
    },
    'lesson-27-gawain-1': {
        'activity_key': 'lesson-27-gawain-1', 'session_number': 11, 'lesson_number': 27,
        'gawain_number': 1, 'title': 'Rhyming Verses',
        'instruction': 'Read the rhyming verses. Then choose the words that rhyme.',
        'interaction': 'rhyming_verses', 'total_items': 4,
        'items': [
            {'id': 'verse-1', 'title': 'The Cat in the Hat', 'verses': ['The cat wore a hat,', 'He sat on a mat,', 'Next to a big, fluffy rat,', 'Who loved to chat with a fat bat'], 'rhyme_words': ['cat', 'hat', 'sat', 'mat', 'rat', 'chat', 'fat', 'bat'], 'image_path': 'pabasa_app/images/sound_detective/detective_bg.png'},
            {'id': 'verse-2', 'title': 'The Funny Rat', 'verses': ['A silly little rat,', 'Danced with a playful bat,', 'They jumped on a mat,', 'And both got quite fat!'], 'rhyme_words': ['rat', 'bat', 'mat', 'fat'], 'image_path': 'pabasa_app/images/sound_detective/detective_bg.png'},
            {'id': 'verse-3', 'title': 'Pat the Cat', 'verses': ['Pat the cat with a friendly pat,', 'He loves to play and chase his hat,', 'On a sunny day, he’ll sit and sat,', 'Watching the world with a cheerful chat.'], 'rhyme_words': ['pat', 'cat', 'pat', 'hat', 'sat', 'chat'], 'image_path': 'pabasa_app/images/sound_detective/detective_bg.png'},
            {'id': 'verse-4', 'title': 'The Splat', 'verses': ['There was a loud splat on the mat,', 'A little creature fell from the hat,', 'Upside down was the silly cat,', 'Who laughed at the splash with a gentle pat.'], 'rhyme_words': ['splat', 'mat', 'hat', 'cat', 'pat'], 'image_path': 'pabasa_app/images/sound_detective/detective_bg.png'},
        ],
    },
    'lesson-28-gawain-1': {
        'activity_key': 'lesson-28-gawain-1', 'session_number': 12, 'lesson_number': 28,
        'gawain_number': 1, 'title': 'Missing Letter',
        'instruction': 'Write the missing letter.',
        'interaction': 'missing_letter_image_oral', 'total_items': 5,
        'items': [
            {'id': 'sun', 'word': 'sun', 'stem': '__un', 'answer': 's', 'image_path': 'pabasa_app/images/lesson_28/sun.png'},
            {'id': 'bell', 'word': 'bell', 'stem': '__ell', 'answer': 'b', 'image_path': 'pabasa_app/images/lesson_28/bell.png'},
            {'id': 'lion', 'word': 'lion', 'stem': '__ion', 'answer': 'l', 'image_path': 'pabasa_app/images/lesson_28/lion.png'},
            {'id': 'sit', 'word': 'sit', 'stem': '__it', 'answer': 's', 'image_path': 'pabasa_app/images/lesson_28/sit.png'},
            {'id': 'egg', 'word': 'egg', 'stem': '__gg', 'answer': 'e', 'image_path': 'pabasa_app/images/lesson_28/egg.png'},
        ],
    },
    'lesson-28-gawain-2': {
        'activity_key': 'lesson-28-gawain-2', 'session_number': 12, 'lesson_number': 28,
        'gawain_number': 2, 'title': 'Word Identifying',
        'instruction': 'Listen to the word, then say the same word.',
        'interaction': 'word_identifying_oral', 'total_items': 5,
        'items': [
            {'id': 'item-1', 'choices': ['sun', 'sit']},
            {'id': 'item-2', 'choices': ['set', 'let']},
            {'id': 'item-3', 'choices': ['sat', 'met']},
            {'id': 'item-4', 'choices': ['set', 'set']},
            {'id': 'item-5', 'choices': ['lit', 'let']},
        ],
    },
    'lesson-29-gawain-1': {
        'activity_key': 'lesson-29-gawain-1', 'session_number': 13, 'lesson_number': 29,
        'gawain_number': 1, 'title': 'Fill in the Blank',
        'instruction': 'Say the missing word to complete each sentence.',
        'interaction': 'oral_sentence_blank', 'total_items': 5,
        'items': [
            {'id': 'item-1', 'before': 'Matt is on the ', 'after': '.', 'answer': 'list', 'image_path': 'pabasa_app/images/lesson_29/list.png'},
            {'id': 'item-2', 'before': 'The ', 'after': ' man is Matt.', 'answer': 'last', 'image_path': 'pabasa_app/images/lesson_29/last.png'},
            {'id': 'item-3', 'before': 'The ', 'after': ' is green.', 'answer': 'stem', 'image_path': 'pabasa_app/images/lesson_29/stem.png'},
            {'id': 'item-4', 'before': 'Matt sets the grain ', 'after': '.', 'answer': 'mill', 'image_path': 'pabasa_app/images/lesson_29/mill.png'},
            {'id': 'item-5', 'before': 'The city is covered in ', 'after': '.', 'answer': 'fog', 'image_path': 'pabasa_app/images/lesson_29/fog.png'},
        ],
    },
    'lesson-29-gawain-2': {
        'activity_key': 'lesson-29-gawain-2', 'session_number': 13, 'lesson_number': 29,
        'gawain_number': 2, 'title': 'Spot the Word',
        'instruction': 'Spot the word challenge. Look carefully at the words inside the box. Listen attentively as the word is read aloud. Find and encircle the word you hear.',
        'interaction': 'spot_word_oral', 'total_items': 9,
        'words': ['mat', 'sell', 'lit', 'till', 'last', 'stem', 'list', 'tell', 'sit'],
    },
    'lesson-30-gawain-1': {
        'activity_key': 'lesson-30-gawain-1', 'session_key': 'session-14',
        'session_number': 14, 'lesson_number': 30, 'gawain_number': 1,
        'title': 'Match It!', 'display_title': 'Session 14 · Lesson 30 · Activity 1',
        'description': 'Read each word, then choose the matching picture.',
        'instruction': 'Read the word aloud first. Then choose the matching picture.',
        'interaction': 'oral_then_picture_word_match', 'sequence_mode': 'per_item',
        'total_items': 5, 'word_bank': ['pet', 'mat', 'pat', 'little', 'happy'],
        # Picture order follows Column B in the workbook reference.
        'items': [
            {'id': 'mat', 'word': 'mat', 'label': 'Mat', 'alt_text': 'A mat', 'image_path': 'pabasa_app/images/lesson_30/mat.png'},
            {'id': 'happy', 'word': 'happy', 'label': 'Happy', 'alt_text': 'A happy person', 'image_path': 'pabasa_app/images/lesson_30/happy.png'},
            {'id': 'pet', 'word': 'pet', 'label': 'Pet', 'alt_text': 'A pet dog', 'image_path': 'pabasa_app/images/lesson_30/pet.png'},
            {'id': 'little', 'word': 'little', 'label': 'Little', 'alt_text': 'A little person', 'image_path': 'pabasa_app/images/lesson_30/little.png'},
            {'id': 'pat', 'word': 'pat', 'label': 'Pat', 'alt_text': 'A hand patting', 'image_path': 'pabasa_app/images/lesson_30/pat.png'},
        ],
    },
    'lesson-30-gawain-2': {
        'activity_key': 'lesson-30-gawain-2', 'session_key': 'session-14',
        'session_number': 14, 'lesson_number': 30, 'gawain_number': 2,
        'title': 'Story Time!', 'display_title': 'Session 14 · Lesson 30 · Activity 2',
        'instruction': 'Listen as the teacher reads the short story. Then read each line aloud.',
        'interaction': 'oral_story_line', 'total_items': 6,
        'story_title': 'Ben and the Little Pet',
        'lines': [
            'Ben has a pet.',
            'It is a little pet.',
            'The pet is on a mat.',
            'Ben pats the pet.',
            'The pet is happy.',
            'Ben is happy too.',
        ],
    },
    'lesson-30-gawain-3': {
        'activity_key': 'lesson-30-gawain-3', 'session_key': 'session-14',
        'session_number': 14, 'lesson_number': 30, 'gawain_number': 3,
        'title': 'Comprehension Check', 'display_title': 'Session 14 · Lesson 30 · Activity 3',
        'instruction': 'Listen to each question. Then choose and encircle the correct answer.',
        'interaction': 'oral_comprehension_choice', 'total_items': 5,
        'questions': [
            {'question': 'Who has a pet?', 'choices': {'a': 'Ben', 'b': 'Hen'}, 'answer': 'a'},
            {'question': 'Where is the pet?', 'choices': {'a': 'net', 'b': 'mat'}, 'answer': 'b'},
            {'question': 'What does Ben do to the pet?', 'choices': {'a': 'pat', 'b': 'sat'}, 'answer': 'a'},
            {'question': 'How does the pet feel?', 'choices': {'a': 'sad', 'b': 'happy'}, 'answer': 'b'},
            {'question': 'How does Ben feel at the end?', 'choices': {'a': 'sad', 'b': 'happy'}, 'answer': 'b'},
        ],
    },
    'lesson-31-gawain-1': {
        'activity_key': 'lesson-31-gawain-1', 'session_key': 'session-15',
        'session_number': 15, 'lesson_number': 31, 'gawain_number': 1,
        'title': 'Circle the Right Word!', 'display_title': 'Session 15 · Lesson 31 · Activity 1',
        'instruction': 'Look at the picture. Circle the correct word.',
        'interaction': 'oral_choice_picture', 'total_items': 5,
        'items': [
            {'id': 'pet', 'image_path': 'pabasa_app/images/lesson_31/pet.png', 'choices': ['pet', 'mat', 'sit'], 'answer': 'pet', 'alt_text': 'A dog'},
            {'id': 'pen', 'image_path': 'pabasa_app/images/lesson_31/pen.png', 'choices': ['mat', 'pen', 'lip'], 'answer': 'pen', 'alt_text': 'A pen'},
            {'id': 'nose', 'image_path': 'pabasa_app/images/lesson_31/nose.png', 'choices': ['pen', 'nose', 'sun'], 'answer': 'nose', 'alt_text': 'A nose'},
            {'id': 'bat', 'image_path': 'pabasa_app/images/lesson_31/bat.png', 'choices': ['bat', 'bit', 'bin'], 'answer': 'bat', 'alt_text': 'A bat'},
            {'id': 'lip', 'image_path': 'pabasa_app/images/lesson_31/lip.png', 'choices': ['sad', 'sit', 'lip'], 'answer': 'lip', 'alt_text': 'Lips'},
        ],
    },
    'lesson-13-gawain-1': {
        'activity_key': 'lesson-13-gawain-1',
        'session_number': 5,
        'lesson_number': 13,
        'gawain_number': 1,
        'title': 'Sabihin ang tunog ng mga letra',
        'instruction': 'Sabihin ang tunog ng mga letra sa ibaba. Lagyan ng tsek (✓) kung tama ang pagkakabigay ng tunog ng mag-aaral.',
        'competencies': ['Phonics', 'Phonological Awareness'],
        'interaction': 'teacher_letter_sound_check',
        'items': [
            {'letter': 'L', 'word': 'liyon', 'image_path': 'pabasa_app/images/alpabetong_pilipino/liyon.png'},
            {'letter': 'l', 'word': 'liyon', 'image_path': 'pabasa_app/images/alpabetong_pilipino/liyon.png'},
            {'letter': 'K', 'word': 'keso', 'image_path': 'pabasa_app/images/alpabetong_pilipino/cheese.png'},
            {'letter': 'k', 'word': 'keso', 'image_path': 'pabasa_app/images/alpabetong_pilipino/cheese.png'},
        ],
    },
    'lesson-13-gawain-2': {
        'activity_key': 'lesson-13-gawain-2', 'session_number': 5, 'lesson_number': 13,
        'gawain_number': 2, 'title': 'I-decode o basahin ang salita',
        'instruction': 'I-decode o basahin nang mag-isa ang mga salita na nasa ibaba. Lagyan ng tsek (✓) kung tama ang pagkaka-decode o basa ng bawat salita.',
        'competencies': ['Phonological Awareness'], 'interaction': 'teacher_word_decode_preview',
        'items': [{'word': 'lola'}, {'word': 'Koko'}, {'word': 'kala'}, {'word': 'ulo'}, {'word': 'keso'}, {'word': 'kili'}, {'word': 'lata'}, {'word': 'luma'}, {'word': 'kuko'}],
    },
    'lesson-13-gawain-3': {
        'activity_key': 'lesson-13-gawain-3', 'session_number': 5, 'lesson_number': 13,
        'gawain_number': 3, 'title': 'I-decode o basahin ang mga pangungusap',
        'instruction': 'I-decode o basahin ang mga pangungusap na nasa ibaba. Lagyan ng tsek (✓) kung tama ang pagkaka-decode o basa ng mga pangungusap.',
        'competencies': ['Phonics', 'Phonological Awareness', 'Fluency'], 'interaction': 'teacher_sentence_decode_preview',
        'items': [
            {'sentence': 'Si Lili ay may laso.'}, {'sentence': 'Ang laso ay Lila.'},
            {'sentence': 'Ang laso ay luma.'}, {'sentence': 'Baka kay lola ang laso ni Lili.'},
            {'sentence': 'May keso sa mesa.'}, {'sentence': 'May kuko ang isa.'},
            {'sentence': 'Ang lata ni Koko.'},
        ],
    },
    'lesson-13-gawain-4': {
        'activity_key': 'lesson-13-gawain-4', 'session_number': 5, 'lesson_number': 13,
        'gawain_number': 4, 'title': 'Pagsusulat ng letrang Ll at Kk',
        'instruction': 'Isulat ang letrang Ll at Kk sa mga guhit.',
        'competencies': ['Phonics'], 'interaction': 'teacher_handwriting_preview',
        'items': [{'letter': 'L'}, {'letter': 'l'}, {'letter': 'K'}, {'letter': 'k'}],
    },
    'lesson-14-gawain-1': {
        'activity_key': 'lesson-14-gawain-1', 'session_number': 5, 'lesson_number': 14,
        'gawain_number': 1, 'title': 'Tukuyin ang tunog /t/ at /n/',
        'instruction': 'Tingnan ang larawan. Isulat ang T kung ang pangalan ng nasa larawan ay nagsisimula sa tunog na /t/, at N kung ito ay nagsisimula sa tunog na /n/.',
        'competencies': ['Phonics', 'Phonological Awareness', 'Vocabulary'],
        'interaction': 'teacher_initial_sound_check',
        'items': [
            {'prompt': '___ iyog', 'word': 'niyog', 'answer': 'N', 'image_path': 'pabasa_app/prescribed/audio/SESSION_5/LESSON_14/GAWAIN_1/niyog.png', 'audio_filename': 'niyog_s5-l14-g1.mp3'},
            {'prompt': '___ ota', 'word': 'nota', 'answer': 'N', 'image_path': 'pabasa_app/prescribed/audio/SESSION_5/LESSON_14/GAWAIN_1/nota.jpg', 'audio_filename': 'nota_s5-l14-g1.mp3'},
            {'prompt': '___ abo', 'word': 'tabo', 'answer': 'T', 'image_path': 'pabasa_app/prescribed/audio/SESSION_5/LESSON_14/GAWAIN_1/tabo.jpg', 'audio_filename': 'tabo_s5-l14-g1.mp3'},
            {'prompt': '___ asa', 'word': 'tasa', 'answer': 'T', 'image_path': 'pabasa_app/prescribed/audio/SESSION_5/LESSON_14/GAWAIN_1/tasa.jpg', 'audio_filename': 'tasa_s5-l14-g1.mp3'},
            {'prompt': '___ ars', 'word': 'nars', 'answer': 'N', 'image_path': 'pabasa_app/prescribed/audio/SESSION_5/LESSON_14/GAWAIN_1/nars.jpg', 'audio_filename': 'nars_s5-l14-g1.mp3'},
        ],
    },
    'session-4-gawain-1': {'activity_key': 'session-4-gawain-1', 'session_number': 4, 'lesson_number': '10, 11, at 12', 'gawain_number': 1, 'title': 'Gawain 1: Tunog ng mga Letra', 'instruction': 'Piliin ang tamang tunog para sa bawat letra.', 'route_name': 'session_4_gawain_1_page', 'total_items': 4, 'interaction': 'letter_sound', 'items': [{'word': 'Tunog ng mga Letra', 'image_path': 'pabasa_app/images/sound_detective/detective_bg.png'}]},
    'session-4-gawain-2': {'activity_key': 'session-4-gawain-2', 'session_number': 4, 'lesson_number': '10, 11, at 12', 'gawain_number': 2, 'title': 'Gawain 2: Pagsamahin ang mga Tunog', 'instruction': 'Pagsamahin ang mga tunog upang mabuo ang salita.', 'route_name': 'session_4_gawain_2_page', 'total_items': 4, 'interaction': 'syllable_blending', 'items': [{'word': 'Pagsamahin ang mga Tunog', 'image_path': 'pabasa_app/images/sound_detective/detective_bg.png'}]},
    'session-4-gawain-3': {'activity_key': 'session-4-gawain-3', 'session_number': 4, 'lesson_number': '10, 11, at 12', 'gawain_number': 3, 'title': 'Gawain 3: I-Decode ang mga Salita', 'instruction': 'Basahin at i-decode ang bawat salita.', 'route_name': 'session_4_gawain_3_page', 'total_items': 9, 'interaction': 'word_decoding', 'items': [{'word': 'I-Decode ang mga Salita', 'image_path': 'pabasa_app/images/word-decoding-bg.jpg'}]},
    'session-4-gawain-4': {'activity_key': 'session-4-gawain-4', 'session_number': 4, 'lesson_number': '10, 11, at 12', 'gawain_number': 4, 'title': 'Gawain 4: I-Decode ang mga Pangungusap', 'instruction': 'Basahin at i-decode ang bawat pangungusap.', 'route_name': 'session_4_gawain_4_page', 'total_items': 4, 'interaction': 'sentence_decoding', 'items': [{'word': 'I-Decode ang mga Pangungusap', 'image_path': 'pabasa_app/images/word-decoding-bg.jpg'}]},
    'lesson7-gawain4a': {
        'activity_key': 'lesson7-gawain4a', 'session_key': 'session-3', 'session_number': 3,
        'lesson_number': 7, 'gawain_number': '4A', 'title': 'GAWAIN 4A: Letrang Oo',
        'instruction': 'I-drag ang parisukat sa MALAKING O. I-drag ang bilog sa maliit na o.',
        'interaction': 'shape_stamp',
        'cells': [
            {'id': 'r1c1', 'letter': 'O', 'answer': 'square'}, {'id': 'r1c2', 'letter': 'a', 'answer': None}, {'id': 'r1c3', 'letter': 'o', 'answer': 'circle'},
            {'id': 'r2c1', 'letter': 'S', 'answer': None}, {'id': 'r2c2', 'letter': 'M', 'answer': None}, {'id': 'r2c3', 'letter': 'M', 'answer': None},
            {'id': 'r3c1', 'letter': 'O', 'answer': 'square'}, {'id': 'r3c2', 'letter': 'I', 'answer': None}, {'id': 'r3c3', 'letter': 'O', 'answer': 'square'},
            {'id': 'r4c1', 'letter': 's', 'answer': None}, {'id': 'r4c2', 'letter': 'o', 'answer': 'circle'}, {'id': 'r4c3', 'letter': 'A', 'answer': None},
        ],
        'answer_mapping': {'r1c1': 'square', 'r1c3': 'circle', 'r3c1': 'square', 'r3c3': 'square', 'r4c2': 'circle'},
    },
    'lesson7-gawain4': {
        'activity_key': 'lesson7-gawain4', 'session_number': 3, 'lesson_number': 7,
        'gawain_number': 4, 'title': 'GAWAIN 4: Letrang Oo', 'instruction': 'Magsanay Magsulat',
        'interaction': 'handwriting',
        'items': [
            {'word': 'Oo', 'stem': '', 'answer': '', 'image_path': 'pabasa_app/images/letrang_o/orasan.png'},
            {'word': 'Oo', 'stem': '', 'answer': '', 'image_path': 'pabasa_app/images/letrang_o/orasan.png'},
            {'word': 'Oo', 'stem': '', 'answer': '', 'image_path': 'pabasa_app/images/letrang_o/orasan.png'},
        ],
    },
    'lesson8-gawain1': {
        'activity_key': 'lesson8-gawain1', 'session_key': 'session-3', 'session_number': 3, 'lesson_number': 8,
        'gawain_number': 1, 'title': 'GAWAIN 1: Letrang Ee', 'instruction': 'Magsanay Magsulat',
        'interaction': 'handwriting',
        'items': [
            {'word': 'Ee', 'stem': '', 'answer': '', 'image_path': 'pabasa_app/images/letrang_e/gawain_1a/elepante.png'},
            {'word': 'Ee', 'stem': '', 'answer': '', 'image_path': 'pabasa_app/images/letrang_e/gawain_1a/eroplano.png'},
            {'word': 'Ee', 'stem': '', 'answer': '', 'image_path': 'pabasa_app/images/letrang_e/gawain_1a/espada.png'},
        ],
    },
    'lesson8-gawain1a': {
        'activity_key': 'lesson8-gawain1a', 'session_key': 'session-3', 'session_number': 3, 'lesson_number': 8,
        'gawain_number': '1A', 'title': 'GAWAIN 1A: Letrang Ee',
        'instruction': 'Panuto: I-click ang larawang nagsisimula sa titik Ee.',
        'interaction': 'picture_selection_with_oral_reading',
        'items': [
            {'word':'elesi','image_path':'pabasa_app/images/letrang_e/gawain_1a/elesi.png','target':True}, {'word':'sasakyan','image_path':'pabasa_app/images/letrang_e/gawain_1a/sasakyan.png','target':False}, {'word':'palaka','image_path':'pabasa_app/images/letrang_e/gawain_1a/palaka.png','target':False}, {'word':'puno','image_path':'pabasa_app/images/letrang_e/gawain_1a/puno.png','target':False}, {'word':'elepante','image_path':'pabasa_app/images/letrang_e/gawain_1a/elepante.png','target':True}, {'word':'isda','image_path':'pabasa_app/images/letrang_e/gawain_1a/isda.png','target':False}, {'word':'eroplano','image_path':'pabasa_app/images/letrang_e/gawain_1a/eroplano.png','target':True}, {'word':'espada','image_path':'pabasa_app/images/letrang_e/gawain_1a/espada.png','target':True}, {'word':'selpon','image_path':'pabasa_app/images/letrang_e/gawain_1a/selpon.png','target':False},
        ],
    },
    'lesson9-gawain1': {
        'activity_key': 'lesson9-gawain1', 'session_key': 'session-3', 'session_number': 3,
        'lesson_number': 9, 'gawain_number': 1, 'title': 'GAWAIN 1: Letrang Ii, Oo, Ee',
        'instruction': 'Basahin ang mga pantig na nasa loob ng kahon.',
        'interaction': 'syllable_blending_with_oral_reading',
        'card_image_path': 'pabasa_app/images/sound_detective/detective_bg.png',
        'items': [
            {'syllables': ['A', 'mi'], 'word': 'Ami'},
            {'syllables': ['Mi', 'mi'], 'word': 'Mimi'},
            {'syllables': ['a', 'so'], 'word': 'aso'},
            {'syllables': ['mi', 'so'], 'word': 'miso'},
            {'syllables': ['me', 'me'], 'word': 'meme'},
            {'syllables': ['si', 'si'], 'word': 'sisi'},
            {'syllables': ['mo', 'mo'], 'word': 'momo'},
            {'syllables': ['si', 'so'], 'word': 'siso'},
            {'syllables': ['mi', 'sa'], 'word': 'misa'},
            {'syllables': ['ma', 'so'], 'word': 'maso'},
            {'syllables': ['ma', 'is'], 'word': 'mais'},
        ],
    },
    'lesson9-gawain2': {
        'activity_key': 'lesson9-gawain2', 'session_key': 'session-3', 'session_number': 3,
        'lesson_number': 9, 'gawain_number': 2, 'title': 'GAWAIN 2: Letrang Ii, Oo, Ee',
        'instruction': 'Tukuyin at Basahin ang pangalan ng mga larawan.',
        'interaction': 'initial_syllable_picture_selection_with_oral_reading',
        'card_image_path': 'pabasa_app/images/sound_detective/detective_bg.png',
        'rows': [
            {'reference':'me','items':[('pari',False),('sopas',False),('mesa',True)]},
            {'reference':'mo','items':[('motor',True),('musika',False),('sultan',False)]},
            {'reference':'si','items':[('santol',False),('isla',False),('sibuyas',True)]},
            {'reference':'is','items':[('upuan',False),('isda',True),('salamin',False)]},
            {'reference':'es','items':[('espada',True),('sinturon',False),('simbahan',False)]},
        ],
    },
    'lesson9-gawain3': {
        'activity_key': 'lesson9-gawain3', 'session_key': 'session-3', 'session_number': 3,
        'lesson_number': 9, 'gawain_number': 3, 'title': 'GAWAIN 3: Letrang Ii, Oo, Ee',
        'instruction': 'Basahin ang mga salita at pangungusap.',
        'interaction': 'oral_reading_sequence',
        'items': [
            {'word': 'mi'}, {'word': 'si'}, {'word': 'is'}, {'word': 'mo'}, {'word': 'me'},
            {'word': 'se'}, {'word': 'miso'}, {'word': 'mais'}, {'word': 'amo'}, {'word': 'siso'},
            {'word': 'Si Ami'}, {'word': 'Si Mimi'}, {'word': 'Ang aso'},
            {'word': 'Ang aso ay isasama.'}, {'word': 'Si Mimi ay sasama sa ama.'},
        ],
    },
    'lesson7-gawain3': {
        'activity_key': 'lesson7-gawain3', 'session_number': 3, 'lesson_number': 7,
        'gawain_number': 3, 'title': 'Gawain 3: Letrang Oo',
        'instruction': 'Ikahon ang larawang may unang tunog na nasa unang kolum.',
        'interaction': 'target_picture_selection_with_oral_reading',
        'targets': [
            {'letter': 'O', 'items': [{'word': 'ulap', 'image_path': 'pabasa_app/images/letrang_o/ulap.png'}, {'word': 'orasan', 'image_path': 'pabasa_app/images/letrang_o/orasan.png'}, {'word': 'ulan', 'image_path': 'pabasa_app/images/letrang_o/ulan.png'}], 'answer': 1},
            {'letter': 'I', 'items': [{'word': 'ilaw', 'image_path': 'pabasa_app/images/letrang_o/ilaw.png'}, {'word': 'elepante', 'image_path': 'pabasa_app/images/letrang_o/elepante.png'}, {'word': 'elesi', 'image_path': 'pabasa_app/images/letrang_o/elesi.png'}], 'answer': 0},
            {'letter': 'M', 'items': [{'word': 'manok', 'image_path': 'pabasa_app/images/letrang_o/manok.png'}, {'word': 'durian', 'image_path': 'pabasa_app/images/letrang_o/durian.png'}, {'word': 'ngipin', 'image_path': 'pabasa_app/images/letrang_o/ngipin.png'}], 'answer': 0},
            {'letter': 'S', 'items': [{'word': 'kandila', 'image_path': 'pabasa_app/images/letrang_o/kandila.png'}, {'word': 'pamaypay', 'image_path': 'pabasa_app/images/letrang_o/pamaypay.png'}, {'word': 'sandok', 'image_path': 'pabasa_app/images/letrang_o/sandok.png'}], 'answer': 2},
            {'letter': 'A', 'items': [{'word': 'isa', 'image_path': 'pabasa_app/images/letrang_o/isa.png'}, {'word': 'apoy', 'image_path': 'pabasa_app/images/letrang_o/apoy.png'}, {'word': 'okra', 'image_path': 'pabasa_app/images/letrang_o/okra.png'}], 'answer': 1},
        ],
        'items': [
            {'word': 'ulap', 'image_path': 'pabasa_app/images/letrang_o/ulap.png'},
            {'word': 'ilaw', 'image_path': 'pabasa_app/images/letrang_o/ilaw.png'},
            {'word': 'manok', 'image_path': 'pabasa_app/images/letrang_o/manok.png'},
            {'word': 'kandila', 'image_path': 'pabasa_app/images/letrang_o/kandila.png'},
            {'word': 'isa', 'image_path': 'pabasa_app/images/letrang_o/isa.png'},
        ],
    },
    'lesson7-gawain2b': {
        'activity_key': 'lesson7-gawain2b', 'session_number': 3, 'lesson_number': 7,
        'gawain_number': '2B', 'title': 'Gawain 2B: Letrang Ii',
        'instruction': 'Bilugan ang larawang nagsisimula sa titik Ii.',
        'interaction': 'picture_selection_with_oral_reading',
        'items': [
            {'word': 'ilog', 'image_path': 'pabasa_app/images/letrang_i/letrang_i_3/ilog.png', 'target': True},
            {'word': 'ipis', 'image_path': 'pabasa_app/images/letrang_i/letrang_i_3/ipis.png', 'target': True},
            {'word': 'ibon', 'image_path': 'pabasa_app/images/letrang_i/letrang_i_3/ibon.png', 'target': True},
            {'word': 'atis', 'image_path': 'pabasa_app/images/letrang_i/letrang_i_3/atis.png', 'target': False},
            {'word': 'mais', 'image_path': 'pabasa_app/images/letrang_i/letrang_i_3/mais.png', 'target': False},
            {'word': 'mangga', 'image_path': 'pabasa_app/images/letrang_i/letrang_i_3/mangga.png', 'target': False},
        ],
    },
    'lesson7-gawain2a': {
        'activity_key': 'lesson7-gawain2a', 'session_number': 3, 'lesson_number': 7,
        'gawain_number': '2A', 'title': 'Gawain 2A: Letrang Ii',
        'instruction': 'Isulat ang i sa kahon ng bagay na nagsisimula sa /i/.',
        'interaction': 'picture_handwriting_with_oral_reading',
        'items': [
            {'word': 'ilaw', 'image_path': 'pabasa_app/images/letrang_i/letrang_i_2/ilaw.png', 'target': True},
            {'word': 'itlog', 'image_path': 'pabasa_app/images/letrang_i/letrang_i_2/itlog.png', 'target': True},
            {'word': 'isa', 'image_path': 'pabasa_app/images/letrang_i/letrang_i_2/isa.png', 'target': True},
            {'word': 'bahay', 'image_path': 'pabasa_app/images/letrang_i/letrang_i_2/bahay.png', 'target': False},
            {'word': 'bola', 'image_path': 'pabasa_app/images/letrang_i/letrang_i_2/bola.png', 'target': False},
            {'word': 'suklay', 'image_path': 'pabasa_app/images/letrang_i/letrang_i_2/suklay.png', 'target': False},
        ],
    },
    'lesson7-gawain2c': {
        'activity_key': 'lesson7-gawain2c',
        'session_number': 3,
        'lesson_number': 7,
        'gawain_number': '2C',
        'title': 'GAWAIN 2: Letrang Ii',
        'instruction': 'Magsanay Magsulat',
        'interaction': 'handwriting',
        'items': [{'word': 'Ii', 'stem': '', 'answer': '', 'image_path': 'pabasa_app/images/letrang_i/ilaw.png'}, {'word': 'Ii', 'stem': '', 'answer': '', 'image_path': 'pabasa_app/images/letrang_i/itlog.png'}, {'word': 'Ii', 'stem': '', 'answer': '', 'image_path': 'pabasa_app/images/letrang_i/ilong.png'}],
    },
    'lesson-16-gawain-1': {
        'activity_key': 'lesson-16-gawain-1',
        'session_number': 6,
        'lesson_number': 16,
        'gawain_number': 1,
        'title': 'Nawawalang Pantig',
        'instruction': 'Bilugan ang nawawalang pantig para sa larawan.',
        'interaction': 'choice',
        'items': [
            {'word': 'gumamela', 'stem': 'mamela', 'choices': ['ga', 'nga', 'gu'], 'answer': 'gu'},
            {'word': 'banga', 'stem': 'nga', 'choices': ['da', 'ba', 'bu'], 'answer': 'ba'},
            {'word': 'gusali', 'stem': 'sali', 'choices': ['gu', 'ngu', 'gi'], 'answer': 'gu'},
            {'word': 'ngiti', 'stem': 'ti', 'choices': ['ngu', 'nge', 'ngi'], 'answer': 'ngi'},
            {'word': 'gata', 'stem': 'ta', 'choices': ['ga', 'gi', 'ngo'], 'answer': 'ga'},
        ],
    },
    'lesson-16-gawain-2': {
        'activity_key': 'lesson-16-gawain-2',
        'session_number': 6,
        'lesson_number': 16,
        'gawain_number': 2,
        'title': 'Punan ang Pantig',
        'instruction': 'Punan ang pantig para mabuo ang ngalan ng mga larawan.',
        'interaction': 'written',
        'items': [
            {'word': 'gumamela', 'stem': 'mamela', 'answer': 'gu'},
            {'word': 'banga', 'stem': 'nga', 'answer': 'ba'},
            {'word': 'gusali', 'stem': 'sali', 'answer': 'gu'},
            {'word': 'ngiti', 'stem': 'ti', 'answer': 'ngi'},
            {'word': 'gata', 'stem': 'ta', 'answer': 'ga'},
        ],
    },
    'lesson-16-gawain-3': {
        'activity_key': 'lesson-16-gawain-3',
        'session_number': 6,
        'lesson_number': 16,
        'gawain_number': 3,
        'title': 'Ikabit ang Wastong Salita',
        'instruction': 'Ikabit ang wastong salita para sa mga larawan.',
        'interaction': 'picture_word_match',
        # The word-bank order follows the numbered workbook list.  The image
        # order follows the right-hand illustration column in the worksheet.
        'word_bank': ['panga', 'gamot', 'sanga', 'bunga', 'goma'],
        'items': [
            {'id': 'picture-1', 'word': 'sanga'},
            {'id': 'picture-2', 'word': 'goma'},
            {'id': 'picture-3', 'word': 'bunga'},
            {'id': 'picture-4', 'word': 'panga'},
            {'id': 'picture-5', 'word': 'gamot'},
        ],
    },
    'session-6-lesson-16-gawain-4': {
        # This is the sole workbook definition used by both the teacher
        # picker/preview and the learner activity.  Keep this order fixed.
        'activity_key': 'session-6-lesson-16-gawain-4',
        'session_key': 'session-6',
        'session_number': 6,
        'lesson_number': 16,
        'gawain_number': 4,
        'title': 'Lesson 16: Gawain 4',
        'description': 'Isulat ang wastong Filipino na salita para sa bawat larawan.',
        'instruction': 'Isulat ang wastong salita para sa larawan.',
        'competencies': ['Phonics', 'Phonological Awareness', 'Vocabulary'],
        'interaction': 'picture_word_write',
        'total_items': 5,
        'thumbnail': 'pabasa_app/images/lesson_16/gamot.png',
        'items': [
            {'word': 'gamot', 'answer': 'gamot', 'letter_count': 5, 'alt_text': 'Larawan ng gamot', 'read_aloud': 'gamot'},
            {'word': 'bunga', 'answer': 'bunga', 'letter_count': 5, 'alt_text': 'Larawan ng bunga', 'read_aloud': 'bunga'},
            {'word': 'panga', 'answer': 'panga', 'letter_count': 5, 'alt_text': 'Larawan ng panga', 'read_aloud': 'panga'},
            {'word': 'goma', 'answer': 'goma', 'letter_count': 4, 'alt_text': 'Larawan ng goma', 'read_aloud': 'goma'},
            {'word': 'sanga', 'answer': 'sanga', 'letter_count': 5, 'alt_text': 'Larawan ng sanga', 'read_aloud': 'sanga'},
        ],
    },
    'lesson-17-18-gawain-5': {
        'activity_key': 'lesson-17-18-gawain-5', 'session_key': 'session-6', 'session_number': 6,
        'lesson_number': '17 at 18', 'gawain_number': 5, 'title': 'Lesson 17 at 18: Gawain 5',
        'description': 'Ikabit ang bawat larawan sa tamang simulang pantig.',
        'instruction': 'Ikabit ng linya mula sa mga larawan sa kaliwa papunta sa simulang pantig na nasa kanan.',
        'competencies': ['Phonics', 'Phonological Awareness', 'Vocabulary'], 'interaction': 'picture_syllable_match', 'total_items': 5,
        'thumbnail': 'pabasa_app/images/picture_word/prescribe_sets/Set B/Robot-Robot.png', 'word_bank': ['ri', 'pu', 'ro', 'pa', 'pi'],
        'items': [
            {'id': 'robot', 'word': 'ro', 'label': 'robot', 'alt_text': 'Larawan ng robot', 'image_path': 'pabasa_app/images/picture_word/prescribe_sets/Set B/Robot-Robot.png'},
            {'id': 'payong', 'word': 'pa', 'label': 'payong', 'alt_text': 'Larawan ng payong', 'image_path': 'pabasa_app/images/picture_word/prescribe_sets/Set B/Umbrella-Payong.png'},
            {'id': 'pitaka', 'word': 'pi', 'label': 'pitaka', 'alt_text': 'Larawan ng pitaka', 'image_path': 'pabasa_app/images/picture_word/prescribe_sets/Set B/Wallet-Pitaka.png'},
            {'id': 'riles', 'word': 'ri', 'label': 'riles', 'alt_text': 'Larawan ng riles', 'image_path': 'pabasa_app/images/picture_word/prescribe_sets/Set B/Railway-Riles.png'},
            {'id': 'puso', 'word': 'pu', 'label': 'puso', 'alt_text': 'Larawan ng puso', 'image_path': 'pabasa_app/images/picture_word/prescribe_sets/Set B/Heart-Puso.png'},
        ],
    },
    'lesson-17-18-gawain-6': {
        # One canonical workbook definition: the teacher picker/preview and
        # learner page deliberately consume this exact ordered data.
        'activity_key': 'lesson-17-18-gawain-6', 'session_key': 'session-6',
        'session_number': 6, 'lesson_number': '17 at 18', 'gawain_number': 6,
        'title': 'Punan ang Nawawalang Pantig',
        'description': 'Basahin ang larawan, pagkatapos punan ang nawawalang pantig.',
        'instruction': 'Basahin ang ngalan ng larawan. Pagkatapos, punan ang nawawalang pantig.',
        'competencies': ['Phonics', 'Phonological Awareness', 'Vocabulary'],
        'interaction': 'oral_then_missing_syllable', 'total_items': 5,
        'thumbnail': 'pabasa_app/images/picture_word/custom/Cat-Pusa.png',
        'items': [
            {'id': 'pusa', 'word': 'PUSA', 'stem': '__sa', 'answer': 'pu', 'alt_text': 'Larawan ng pusa', 'image_path': 'pabasa_app/images/picture_word/custom/Cat-Pusa.png'},
            {'id': 'pako', 'word': 'PAKO', 'stem': 'pa__', 'answer': 'ko', 'alt_text': 'Larawan ng pako', 'image_path': 'pabasa_app/images/prescribed_gawain_6/Pako.png'},
            {'id': 'paruparo', 'word': 'PARUPARO', 'stem': 'parupa__', 'answer': 'ro', 'alt_text': 'Larawan ng paruparo', 'image_path': 'pabasa_app/images/picture_word/custom/Butterfly-Paruparo.png'},
            {'id': 'rosas', 'word': 'ROSAS', 'stem': '__sas', 'answer': 'ro', 'alt_text': 'Larawan ng rosas', 'image_path': 'pabasa_app/images/prescribed_gawain_6/Rosas.png'},
            {'id': 'kariton', 'word': 'KARITON', 'stem': 'ka__ton', 'answer': 'ri', 'alt_text': 'Larawan ng kariton', 'image_path': 'pabasa_app/images/prescribed_gawain_6/Kariton.png'},
        ],
    },
    'lesson-17-18-gawain-7': {
        # Canonical workbook definition shared by the course preview, learner
        # page and server-side answer validation.  Do not reorder either list.
        'activity_key': 'lesson-17-18-gawain-7', 'session_key': 'session-6',
        'session_number': 6, 'lesson_number': '17 at 18', 'gawain_number': 7,
        'title': 'Ikabit ang Larawan sa Ngalan Nito',
        'display_title': 'Lesson 17 at 18: Gawain 7',
        'description': 'Basahin ang mga ngalan at ikabit ang bawat larawan sa tamang salita.',
        'instruction': 'Basahin muna ang mga ngalan. Pagkatapos, ikabit ang bawat larawan sa tamang ngalan nito.',
        'workbook_instruction': 'Ikabit na linya ang mga larawan mula sa kaliwa sa ngalan nila sa kanan.',
        'teacher_guidance': 'Babasa muna ang mag-aaral ng bawat ngalan bago niya maikabit ang larawan sa tamang salita.',
        'competencies': ['Phonics', 'Phonological Awareness', 'Vocabulary'],
        'interaction': 'oral_then_picture_word_match', 'total_items': 10,
        'thumbnail': 'pabasa_app/images/picture_word/prescribe_sets/Set B/Robot-Robot.png',
        'word_bank': ['riles', 'puso', 'robot', 'payong', 'pitaka'],
        'items': [
            {'id': 'robot', 'word': 'robot', 'label': 'Robot', 'alt_text': 'Larawan ng robot', 'image_path': 'pabasa_app/images/picture_word/prescribe_sets/Set B/Robot-Robot.png'},
            {'id': 'payong', 'word': 'payong', 'label': 'Payong', 'alt_text': 'Larawan ng payong', 'image_path': 'pabasa_app/images/picture_word/prescribe_sets/Set B/Umbrella-Payong.png'},
            {'id': 'pitaka', 'word': 'pitaka', 'label': 'Pitaka', 'alt_text': 'Larawan ng pitaka', 'image_path': 'pabasa_app/images/picture_word/prescribe_sets/Set B/Wallet-Pitaka.png'},
            {'id': 'riles', 'word': 'riles', 'label': 'Riles', 'alt_text': 'Larawan ng riles', 'image_path': 'pabasa_app/images/picture_word/prescribe_sets/Set B/Railway-Riles.png'},
            {'id': 'puso', 'word': 'puso', 'label': 'Puso', 'alt_text': 'Larawan ng puso', 'image_path': 'pabasa_app/images/picture_word/prescribe_sets/Set B/Heart-Puso.png'},
        ],
    },
    'lesson-17-18-gawain-8': {
        # Single workbook source for the teacher preview, learner UI and validation.
        'activity_key': 'lesson-17-18-gawain-8', 'session_key': 'session-6',
        'session_number': 6, 'lesson_number': '17 at 18', 'gawain_number': 8,
        'title': 'Bilugan ang Naiibang Salita', 'display_title': 'Lesson 17 at 18: Gawain 8',
        'description': 'Basahin ang bawat pangkat at piliin ang salitang naiiba.',
        'instruction': 'Basahin ang mga salita. Pagkatapos, bilugan ang salitang naiiba sa pangkat.',
        'workbook_instruction': 'Bilugan ang naiibang salita sa pangkat.',
        'teacher_guidance': 'Babasa muna ang mag-aaral ng tatlong salita bago pipiliin ang salitang naiiba.',
        'competencies': ['Phonics', 'Phonological Awareness'], 'interaction': 'oral_then_odd_word',
        'total_items': 20, 'thumbnail': 'pabasa_app/images/picture_word/prescribe_sets/Set B/Robot-Robot.png',
        'items': [
            {'id': 'group-1', 'words': ['palaka', 'peluka', 'palaka'], 'answer_index': 1},
            {'id': 'group-2', 'words': ['palaro', 'palara', 'palara'], 'answer_index': 0},
            {'id': 'group-3', 'words': ['resibo', 'resita', 'resibo'], 'answer_index': 1},
            {'id': 'group-4', 'words': ['pilay', 'pilay', 'palay'], 'answer_index': 2},
            {'id': 'group-5', 'words': ['bareta', 'balita', 'bareta'], 'answer_index': 1},
        ],
    },
}

# Each saved item points directly to its own workbook image file.  Keeping the
# path beside the item also preserves exact image-to-word ordering on every UI.
for _activity in PRESCRIBED_ACTIVITIES.values():
    for _item in _activity.get('items', []):
        if _item.get('word') in LESSON_16_IMAGE_PATHS:
            _item['image_path'] = LESSON_16_IMAGE_PATHS[_item['word']]


def prescribed_activity(activity_key):
    """Return a copy so request handling cannot mutate the shared workbook data."""
    activity = PRESCRIBED_ACTIVITIES.get(str(activity_key or '').strip())
    return deepcopy(activity) if activity else None
