from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    
    # Authentication routes
    path('api/register/teacher/', views.register_teacher, name='register_teacher'),
    path('api/register/teacher/verify-otp/', views.verify_teacher_otp, name='verify_teacher_otp'),
    path('api/register/teacher/resend-otp/', views.resend_teacher_signup_otp, name='resend_teacher_signup_otp'),
    path('api/register/student/', views.register_student, name='register_student'),
    path('api/register/student/verify-otp/', views.verify_student_otp, name='verify_student_otp'),
    path('api/register/student/resend-otp/', views.resend_student_signup_otp, name='resend_student_signup_otp'),
    path('api/login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout'),
    path('api/forgot-password/request/', views.request_password_reset, name='request_password_reset'),
    path('api/forgot-password/verify-otp/', views.verify_forgot_password_otp, name='verify_forgot_password_otp'),
    path('api/forgot-password/reset/', views.reset_password, name='reset_password'),
    path('api/forgot-password/resend-otp/', views.resend_password_reset_otp, name='resend_password_reset_otp'),
    
    path('auth/', views.auth, name='auth'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('forgot-password/otp/', views.forgot_password_otp, name='forgot_password_otp'),
    path('forgot-password/reset/', views.forgot_password_reset, name='forgot_password_reset'),
    path('signup/', views.signup, name='signup'),
    path('signup/teacher/', views.teacher_signup, name='teacher_signup'),
    path('signup/student/', views.student_signup, name='student_signup'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/teacher/', views.dashboard_teacher, name='dashboard_teacher'),
    path('dashboard/admin/', views.dashboard_admin, name='dashboard_admin'),
    path('dashboard/admin/students/', views.admin_students, name='admin_students'),
    path('dashboard/admin/students/<int:user_id>/', views.admin_student_detail, name='admin_student_detail'),
    path('dashboard/admin/students/<int:user_id>/edit/', views.admin_student_edit, name='admin_student_edit'),
    path('dashboard/admin/students/<int:user_id>/archive/', views.admin_student_archive, name='admin_student_archive'),
    path('dashboard/admin/teachers/', views.admin_teachers, name='admin_teachers'),
    path('dashboard/admin/teachers/<int:user_id>/', views.admin_teacher_detail, name='admin_teacher_detail'),
    path('dashboard/admin/teachers/<int:user_id>/edit/', views.admin_teacher_edit, name='admin_teacher_edit'),
    path('dashboard/admin/teachers/<int:user_id>/archive/', views.admin_teacher_archive, name='admin_teacher_archive'),
    path('dashboard/admin/classes/', views.admin_classes, name='admin_classes'),
    path('dashboard/admin/courses/', views.admin_courses, name='admin_courses'),
    path('dashboard/admin/practice-assessment/', views.admin_practice_assessment, name='admin_practice_assessment'),
    path('dashboard/admin/settings/', views.admin_settings, name='admin_settings'),
    path('dashboard/courses/', views.courses, name='courses'),
    path('dashboard/assessment/', views.assessment, name='assessment'),
    path('dashboard/assessment/reading_ui/word/', views.reading_word_page, name='reading_word_page'),
    path('dashboard/assessment/reading_ui/sentence/', views.reading_sentence_page, name='reading_sentence_page'),
    path('dashboard/assessment/reading_ui/para/', views.reading_para_page, name='reading_para_page'),
    path('dashboard/practice/word/', views.practice_word_page, name='practice_word_page'),
    path('dashboard/practice/sentence/', views.practice_sentence_page, name='practice_sentence_page'),
    path('dashboard/practice/paragraph/', views.practice_para_page, name='practice_para_page'),
    path('dashboard/courses/teacher-view/', views.course_teacher_view, name='course_teacher_view'),
    path('dashboard/courses/student-view/', views.course_student_view, name='course_student_view'),
    path('dashboard/students/', views.students, name='students'),
    path('dashboard/students/detail/', views.student_detail, name='student_detail'),
    path('dashboard/calendar/', views.calendar, name='calendar'),
    path('dashboard/settings/', views.settings_view, name='settings'),
    path('dashboard/practice/', views.practice, name='practice'),
    path('dashboard/profile/', views.profile, name='profile'),
    path('dashboard/notifications/', views.notifications, name='notifications'),
    path('what-is-pabasa/', views.pabasa_info, name='pabasa_info'),
    path('about/', views.about, name='about'),
    path('api/join-class/', views.join_class, name='join_class'),
    path('dashboard/teacher/classes/', views.get_teacher_classes, name='get_teacher_classes'),
    path('dashboard/teacher/overview/', views.get_teacher_overview, name='get_teacher_overview'),
    path('dashboard/student/classes/', views.get_student_joined_classes, name='get_student_joined_classes'),
    path('students/send-email/', views.send_parent_email, name='send_parent_email'),
    path('dashboard/student/unenroll/', views.unenroll_class, name='unenroll_class'),
    path('dashboard/teacher/add-material/', views.add_reading_material, name='add_reading_material'),
    path('api/class/materials/', views.get_class_materials, name='get_class_materials'),
    path(
    'dashboard/teacher/create-class/',
    views.create_reading_class,
    name='create_reading_class'
),
    path(
    'dashboard/teacher/delete-class/',
    views.delete_reading_class,
    name='delete_reading_class'
),
    path(
        'dashboard/teacher/manage/',
        views.class_management_view,
        name='class_management'
    ),
    path(
        'dashboard/teacher/update-class/',
        views.update_class_info,
        name='update_class_info'
    ),
    path(
        'dashboard/teacher/add-student-to-class/',
        views.teacher_add_student,
        name='teacher_add_student'
    ),
]
