from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    
    # Authentication routes
    path('api/register/teacher/', views.register_teacher, name='register_teacher'),
    path('api/register/teacher/verify-otp/', views.verify_teacher_otp, name='verify_teacher_otp'),
    path('api/register/teacher/resend-otp/', views.resend_teacher_signup_otp, name='resend_teacher_signup_otp'),
    path('api/register/student/', views.register_student, name='register_student'),
    path('api/register/student/verify-otp/', views.verify_student_otp, name='verify_student_otp'),
    path('api/register/student/resend-otp/', views.resend_student_signup_otp, name='resend_student_signup_otp'),
    path('api/login/', views.login_user, name='login_user'),
    path('account/principal/change-temporary-password/', views.principal_change_temporary_password, name='principal_change_temporary_password'),
    path('logout/', views.logout_user, name='logout'),
    path('api/forgot-password/request/', views.request_password_reset, name='request_password_reset'),
    path('api/forgot-password/verify-otp/', views.verify_forgot_password_otp, name='verify_forgot_password_otp'),
    path('api/forgot-password/reset/', views.reset_password, name='reset_password'),
    path('api/forgot-password/resend-otp/', views.resend_password_reset_otp, name='resend_password_reset_otp'),
    
    path('auth/', views.auth, name='auth'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('forgot-password/otp/', views.forgot_password_otp, name='forgot_password_otp'),
    path('forgot-password/reset/', views.forgot_password_reset, name='forgot_password_reset'),
    path('signup/', views.signup, name='signup'),
    path('signup/teacher/', views.teacher_signup, name='teacher_signup'),
    path('signup/student/', views.student_signup, name='student_signup'),
    path('api/signup/student/sections/', views.student_signup_sections, name='student_signup_sections'),
    path('api/signup/sections/', views.student_signup_sections, name='signup_sections'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/teacher/', views.dashboard_teacher, name='dashboard_teacher'),
    path('dashboard/admin/', views.dashboard_admin, name='dashboard_admin'),
    path('dashboard/admin/students/', views.admin_students, name='admin_students'),
    path('dashboard/admin/students/<int:user_id>/', views.admin_student_detail, name='admin_student_detail'),
    path('dashboard/admin/students/<int:user_id>/edit/', views.admin_student_edit, name='admin_student_edit'),
    path('dashboard/admin/students/<int:user_id>/archive/', views.admin_student_archive, name='admin_student_archive'),
    path('dashboard/admin/students/<int:user_id>/move-enrollment/', views.admin_student_move_enrollment, name='admin_student_move_enrollment'),
    path('dashboard/admin/students/<int:user_id>/enrollment-action/', views.admin_student_archive_action, name='admin_student_archive_action'),
    path('dashboard/admin/students/<int:user_id>/restore/', views.admin_student_restore, name='admin_student_restore'),
    path('dashboard/admin/students/<int:user_id>/prepare-return/', views.admin_student_returning_enrollment, name='admin_student_returning_enrollment'),
    path('dashboard/admin/teachers/', views.admin_teachers, name='admin_teachers'),
    path('dashboard/admin/teachers/<int:user_id>/', views.admin_teacher_detail, name='admin_teacher_detail'),
    path('dashboard/admin/teachers/<int:user_id>/edit/', views.admin_teacher_edit, name='admin_teacher_edit'),
    path('dashboard/admin/teachers/<int:user_id>/archive/', views.admin_teacher_archive, name='admin_teacher_archive'),
    path('dashboard/admin/principals/', views.admin_principals, name='admin_principals'),
    path('dashboard/admin/classes/', views.admin_classes, name='admin_classes'),
    path('dashboard/admin/school/', views.admin_school, name='admin_school'),
    path('dashboard/admin/school/<int:school_id>/', views.admin_school_detail, name='admin_school_detail'),
    path('dashboard/admin/school/<int:school_id>/principal/<int:user_id>/', views.admin_school_principal_detail, name='admin_school_principal_detail'),
    path('dashboard/admin/school/<int:school_id>/principal/<int:user_id>/edit/', views.admin_school_principal_edit, name='admin_school_principal_edit'),
    path('dashboard/admin/school/<int:school_id>/principal/<int:user_id>/reset-password/', views.admin_school_principal_reset_password, name='admin_school_principal_reset_password'),
    path('dashboard/admin/school/<int:school_id>/principal/<int:user_id>/status/', views.admin_school_principal_status, name='admin_school_principal_status'),
    path('dashboard/admin/school/sections/<int:section_id>/', views.admin_school_section_update, name='admin_school_section_update'),
    path('dashboard/admin/classes/<int:section_id>/', views.admin_class_detail, name='admin_class_detail'),
    path('dashboard/admin/classes/<int:section_id>/edit/', views.admin_class_edit, name='admin_class_edit'),
    path('dashboard/admin/classes/<int:section_id>/deactivate/', views.admin_class_deactivate, name='admin_class_deactivate'),
    path('dashboard/admin/courses/', views.admin_courses, name='admin_courses'),
    path('dashboard/admin/courses/<int:material_id>/', views.admin_course_detail, name='admin_course_detail'),
    path('dashboard/admin/courses/<int:material_id>/edit/', views.admin_course_edit, name='admin_course_edit'),
    path('dashboard/admin/courses/<int:material_id>/archive/', views.admin_course_archive, name='admin_course_archive'),
    path('dashboard/admin/calendar/', views.admin_school_calendar, name='admin_school_calendar'),
    path('dashboard/admin/official-reading-assessments/', views.admin_official_reading_assessments, name='admin_official_reading_assessments'),
    path('dashboard/admin/official-reading-assessments/add/', views.admin_official_reading_assessment_add, name='admin_official_reading_assessment_add'),
    path('dashboard/admin/official-reading-assessments/<int:material_id>/', views.admin_official_reading_assessment_detail, name='admin_official_reading_assessment_detail'),
    path('dashboard/admin/official-reading-assessments/<int:material_id>/archive/', views.admin_official_reading_assessment_archive, name='admin_official_reading_assessment_archive'),
    path('dashboard/admin/official-reading-assessments/<int:material_id>/unarchive/', views.admin_official_reading_assessment_unarchive, name='admin_official_reading_assessment_unarchive'),
    path('dashboard/admin/official-reading-assessments/<int:material_id>/delete/', views.admin_official_reading_assessment_delete, name='admin_official_reading_assessment_delete'),
    path('dashboard/admin/practice-assessment/', views.admin_practice_assessment, name='admin_practice_assessment'),
    path('dashboard/admin/practice-assessment/create/', views.admin_practice_create, name='admin_practice_create'),
    path('dashboard/admin/practice-assessment/<int:practice_id>/', views.admin_practice_detail, name='admin_practice_detail'),
    path('dashboard/admin/practice-assessment/<int:practice_id>/edit/', views.admin_practice_edit, name='admin_practice_edit'),
    path('dashboard/admin/practice-assessment/<int:practice_id>/archive/', views.admin_practice_archive, name='admin_practice_archive'),
    path('dashboard/admin/practice-assessment/<int:practice_id>/delete/', views.admin_practice_delete, name='admin_practice_delete'),
    path('dashboard/admin/settings/', views.admin_settings, name='admin_settings'),
    path('dashboard/courses/', views.courses, name='courses'),
    path('dashboard/assessment/', views.assessment, name='assessment'),
    path('api/assessment/request/', views.request_assessment_access, name='request_assessment_access'),
    path('api/teacher/assessment-requests/', views.teacher_assessment_requests, name='teacher_assessment_requests'),
    path('api/teacher/assessment-requests/<int:request_id>/approve/', views.approve_assessment_request, name='approve_assessment_request'),
    path('dashboard/assessment/activate-aral-intervention/', views.activate_aral_intervention, name='activate_aral_intervention'),
    path('dashboard/teacher/students/aral-action/', views.teacher_aral_action, name='teacher_aral_action'),
    path('material/export-results/', views.export_material_results, name='export_material_results'),
    path('assessment/<int:assessment_id>/export-crla/', views.export_crla_assessment, name='export_crla_assessment'),
    path('dashboard/assessment/reading_ui/word/', views.reading_word_page, name='reading_word_page'),
    path('dashboard/assessment/activity/picture-word-matching/', views.picture_word_matching_page, name='picture_word_matching_page'),
    path('dashboard/assessment/activity/letter-sound-matching/', views.letter_sound_matching_page, name='letter_sound_matching_page'),
    path('dashboard/assessment/activity/letter-sound-correspondence/', views.letter_sound_correspondence_page, name='letter_sound_correspondence_page'),
    path('dashboard/assessment/activity/syllable-blending/', views.syllable_blending_page, name='syllable_blending_page'),
    path('dashboard/assessment/activity/clap-count-syllables/', views.clap_count_syllables_page, name='clap_count_syllables_page'),
    path('dashboard/assessment/activity/sound-detective/', views.sound_detective_page, name='sound_detective_page'),
    path('dashboard/assessment/sound-detective/progress/', views.sound_detective_progress, name='sound_detective_progress'),
    path('dashboard/assessment/story-reading/', views.story_reading_page, name='story_reading_page'),
    path('api/story-reading/complete/', views.story_reading_complete, name='story_reading_complete'),
    path('dashboard/assessment/story-response/', views.story_response_page, name='story_response_page'),
    path('dashboard/assessment/story-questions/', views.story_questions_page, name='story_questions_page'),
    path('dashboard/assessment/story-call', views.story_call_page, name='story_call_page'),
    path('api/story-response/submit/', views.story_response_submit, name='story_response_submit'),
    path('api/teacher/story-response/review/', views.teacher_story_response_review, name='teacher_story_response_review'),
    path('api/teacher/story-response/grade/', views.teacher_story_response_grade, name='teacher_story_response_grade'),
    path('api/teacher/story-response/audio/<int:submission_id>/', views.teacher_story_response_audio, name='teacher_story_response_audio'),
    path('api/teacher/published-stories/', views.get_published_stories_api, name='get_published_stories_api'),
    path('api/story-response/prompts/', views.get_story_response_prompts_api, name='get_story_response_prompts_api'),
    path('dashboard/assessment/reading_ui/sentence/', views.reading_sentence_page, name='reading_sentence_page'),
    path('dashboard/assessment/activity/sentence-reading/', views.sentence_bot_page, name='sentence_bot_page'),
    path('api/sentence-bot/complete/', views.sentence_bot_complete, name='sentence_bot_complete'),
    path('dashboard/assessment/activity/phrase-reading/', views.phrase_reading_page, name='phrase_reading_page'),
    path(
        'dashboard/assessment/activity/<slug:activity_slug>/',
        views.aral_template_activity_page,
        name='aral_template_activity_page',
    ),
    path(
        'api/dashboard/assessment/activity/<slug:activity_slug>/complete/',
        views.aral_template_activity_complete,
        name='aral_template_activity_complete',
    ),
    path('dashboard/assessment/reading_ui/para/', views.reading_para_page, name='reading_para_page'),
    path('dashboard/assessment/reading_ui/vowel/', views.reading_vowel_page, name='reading_vowel_page'),
    path('api/reading/transcribe/', views.reading_transcribe_api, name='reading_transcribe_api'),
    path('api/reading/read-aloud/', views.reading_read_aloud_api, name='reading_read_aloud_api'),
    path('api/story-response/read-aloud/', views.story_response_read_aloud_api, name='story_response_read_aloud_api'),
    path('api/story-call/maya-read-aloud/', views.maya_read_aloud_api, name='maya_read_aloud_api'),
    path('api/practice/hunt/award-stars/', views.award_hunt_mode_stars, name='award_hunt_mode_stars'),
    path('dashboard/practice/word/', views.practice_word_page, name='practice_word_page'),
    path('dashboard/practice/sentence/', views.practice_sentence_page, name='practice_sentence_page'),
    path('dashboard/practice/paragraph/', views.practice_para_page, name='practice_para_page'),
    path('dashboard/practice/results/', views.practice_results, name='practice_results'),
    path('dashboard/practice/tutorial/<str:mode>/seen/', views.practice_mark_tutorial_seen, name='practice_mark_tutorial_seen'),
    path('dashboard/practice/progression/<str:mode>/', views.practice_game_progression, name='practice_game_progression'),
    path('dashboard/courses/teacher-view/', views.course_teacher_view, name='course_teacher_view'),
    path('dashboard/courses/student-view/', views.course_student_view, name='course_student_view'),
    path('dashboard/students/', views.students, name='students'),
    path('dashboard/students/detail/', views.student_detail, name='student_detail'),
    path('dashboard/calendar/', views.school_calendar_page, name='calendar'),
    path('dashboard/settings/', views.settings_view, name='settings'),
    path('dashboard/practice/', views.practice, name='practice'),
    path('dashboard/themes/', views.theme_shop, name='theme_shop'),
    path('api/student/themes/', views.student_theme_action, name='student_theme_action'),
    path('dashboard/profile/', views.profile, name='profile'),
    path('dashboard/notifications/', views.notifications, name='notifications'),
    path('api/notifications/', views.get_notifications, name='get_notifications'),
    path('api/notifications/unread-count/', views.get_unread_notification_count, name='get_unread_notification_count'),
    path('api/teacher/assessment-requests/count/', views.get_teacher_assessment_request_count, name='get_teacher_assessment_request_count'),
    path('api/notifications/mark-read/', views.mark_notification_read, name='mark_notification_read'),
    path('api/notifications/clear/', views.clear_notifications, name='clear_notifications'),
    path('api/live-assessment/active-invitation/', views.live_assessment_active_invitation, name='live_assessment_active_invitation'),
    path('api/live-assessment/server-time/', views.live_assessment_server_time, name='live_assessment_server_time'),
    path('record-assessment-completion/', views.record_assessment_completion, name='record_assessment_completion'),
    path('api/assessment/end-state/', views.persist_student_end_assessment_state, name='persist_student_end_assessment_state'),
    path('api/assessment/story-answer/check/', views.check_story_answer_api, name='check_story_answer_api'),
    path('api/assessment/story-answer/transcribe/', views.transcribe_story_answer_api, name='transcribe_story_answer_api'),
    path('api/story-call/complete/', views.story_call_complete_api, name='story_call_complete_api'),
    path('api/story-call/check/', views.story_call_check_answer_api, name='story_call_check_answer_api'),
    path('what-is-pabasa/', views.pabasa_info, name='pabasa_info'),
    path('about/', views.about, name='about'),
    path('faq/', views.faq, name='faq'),
    path('terms/', views.terms, name='terms'),
    path('privacy/', views.privacy, name='privacy'),
    path('dashboard/teacher/classes/', views.get_teacher_classes, name='get_teacher_classes'),
    path('dashboard/teacher/overview/', views.get_teacher_overview, name='get_teacher_overview'),
    # API: authoritative teacher student list (used by frontend JS)
    path('dashboard/teacher/students-api/', views.get_teacher_students_api, name='get_teacher_students_api'),
    # Courses API for teachers
    path('dashboard/teacher/courses/', views.get_teacher_courses_api, name='get_teacher_courses_api'),
    path('dashboard/teacher/assessments/', views.get_teacher_assessments_api, name='get_teacher_assessments_api'),
    path('dashboard/teacher/assessment/<int:assessment_id>/', views.get_teacher_assessment_api, name='get_teacher_assessment_api'),
    path('dashboard/teacher/material-attempts/', views.get_teacher_material_attempts_api, name='get_teacher_material_attempts_api'),
    path('dashboard/teacher/update-assessment/', views.teacher_update_assessment, name='teacher_update_assessment'),
    path('dashboard/teacher/archive-assessment/', views.teacher_archive_assessment, name='teacher_archive_assessment'),
    path('dashboard/teacher/create-course/', views.create_course, name='create_course'),
    path('dashboard/teacher/delete-course/', views.delete_course, name='delete_course'),
    path('dashboard/teacher/course/send-update/', views.send_course_update, name='send_course_update'),
    path('dashboard/teacher/start-live-assessment/', views.start_live_assessment, name='start_live_assessment'),
    path('dashboard/live-assessment/<str:session_id>/', views.live_assessment_session_entry, name='live_assessment_session'),
    path('dashboard/live-assessment/<str:session_id>/control/', views.live_assessment_session_page, name='live_assessment_session_control'),
    path('dashboard/live-assessment/<str:session_id>/waiting/', views.live_assessment_waiting_room_page, name='live_assessment_waiting_room'),
    path('api/live-assessment/session/<str:session_id>/', views.live_assessment_session_state, name='live_assessment_session_state'),
    path('api/live-assessment/session/<str:session_id>/action/', views.live_assessment_session_action, name='live_assessment_session_action'),
    path('api/live-assessment/session/<str:session_id>/student-update/', views.live_assessment_student_state_update, name='live_assessment_student_state_update'),
    path('dashboard/teacher/assist/students/', views.get_assist_students, name='get_assist_students'),
    path('dashboard/teacher/assist/start/', views.start_assist_assessment, name='start_assist_assessment'),
    path('dashboard/student/classes/', views.get_student_joined_classes, name='get_student_joined_classes'),
    path('dashboard/teacher/course/add-material/', views.add_material_to_course, name='add_material_to_course'),
    path('dashboard/teacher/course/remove-material/', views.remove_material_from_course, name='remove_material_from_course'),
    # Backwards-compatible alias: some client-side code expects this API path
    path('api/student/classes/', views.get_student_joined_classes, name='get_student_joined_classes_api'),
    path('students/send-email/', views.send_parent_email, name='send_parent_email'),
    path('dashboard/student/unenroll/', views.unenroll_class, name='unenroll_class'),
    path('dashboard/teacher/extract-material/', views.extract_reading_material_file, name='extract_reading_material_file'),
    path('dashboard/teacher/add-material/', views.add_reading_material, name='add_reading_material'),
    path('api/class/materials/', views.get_class_materials, name='get_class_materials'),
    path(
        'dashboard/teacher/generate-class-code/',
        views.generate_class_code,
        name='generate_class_code',
    ),
    path(
        'dashboard/teacher/create-class/',
        views.create_reading_class,
        name='create_reading_class',
    ),
    path(
    'dashboard/teacher/delete-class/',
    views.delete_reading_class,
    name='delete_reading_class'
),
    path(
        'dashboard/teacher/manage/',
        views.class_management_view,
        name='class_management'
    ),
    path('dashboard/teacher/finalize-student/', views.teacher_finalize_student, name='teacher_finalize_student'),
    path('dashboard/teacher/correct-student-outcome/', views.teacher_correct_student_outcome, name='teacher_correct_student_outcome'),
    path(
        'dashboard/teacher/update-class/',
        views.update_class_info,
        name='update_class_info'
    ),
    path(
        'dashboard/teacher/section/assessment-week/',
        views.update_section_assessment_week,
        name='update_section_assessment_week'
    ),
    path(
        'dashboard/teacher/update-material/',
        views.teacher_update_material,
        name='teacher_update_material'
    ),
    path(
        'dashboard/teacher/toggle-material-access/',
        views.toggle_material_student_access,
        name='toggle_material_student_access'
    ),
    path(
        'dashboard/teacher/delete-material/',
        views.delete_reading_material,
        name='delete_reading_material'
    ),
    path(
        'dashboard/teacher/update-practice/',
        views.teacher_update_practice,
        name='teacher_update_practice'
    ),
    path(
        'dashboard/teacher/delete-practice/',
        views.delete_practice,
        name='delete_practice'
    ),
    path(
        'dashboard/teacher/add-student-to-class/',
        views.teacher_add_student,
        name='teacher_add_student'
    ),
    path(
        'dashboard/teacher/remove-student-from-class/',
        views.teacher_remove_student,
        name='teacher_remove_student'
    ),
    
    # Principal Dashboard Routes
    path('dashboard/principal/', views.dashboard_principal, name='dashboard_principal'),
    path('dashboard/principal/school/', views.principal_school_workspace, name='principal_school_workspace'),
    path('dashboard/principal/school/sections/<int:section_id>/', views.principal_section_detail, name='principal_section_detail'),
    path('dashboard/principal/performance/', views.principal_performance, name='principal_performance'),
    path('dashboard/principal/assessments/', views.principal_assessments, name='principal_assessments'),
    path('dashboard/principal/reports/', views.principal_reports, name='principal_reports'),
    path('dashboard/principal/settings/', views.principal_settings, name='principal_settings'),
    path('dashboard/principal/calendar/', views.principal_calendar, name='principal_calendar'),
]
