"""
Django settings for pabasa_site project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent
load_dotenv(PROJECT_ROOT / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c8tcixn4vam*#z1*^d+9x6ddm89ph_+z%5+jce14vgdr@#*y5t'

# SECURITY WARNING: don't run with debug turned on in production!
def _bool_env(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    normalized = value.strip().lower()
    if normalized in {'1', 'true', 'yes', 'on'}:
        return True
    if normalized in {'0', 'false', 'no', 'off'}:
        return False
    raise ImproperlyConfigured(f'{name} must be true or false.')


DJANGO_ENV = os.environ.get('DJANGO_ENV', 'development').strip().lower()
DEBUG = True

def _csv_env(name):
    value = os.environ.get(name, '')
    return [item.strip() for item in value.split(',') if item.strip()]


def _dedupe(items):
    seen = set()
    output = []
    for item in items:
        if item and item not in seen:
            seen.add(item)
            output.append(item)
    return output


ALLOWED_HOSTS = _dedupe(_csv_env('ALLOWED_HOSTS') + [
    'tupcpabasa.app',
    'www.tupcpabasa.app',
    '127.0.0.1',
    'localhost',
])

CSRF_TRUSTED_ORIGINS = _dedupe(_csv_env('CSRF_TRUSTED_ORIGINS') + [
    'https://tupcpabasa.app',
    'https://www.tupcpabasa.app',
])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "pabasa_app",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'pabasa_app.middleware.PrincipalPasswordChangeMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pabasa_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pabasa_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
SITE_URL = os.environ.get('SITE_URL', 'https://tupcpabasa.app')

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

if DJANGO_ENV == 'production':
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True

# Email settings. Gmail SMTP over STARTTLS is the existing production provider.
# Development defaults to the in-memory backend so a missing/blocked SMTP
# connection is never mistaken for a configured local dependency. Set
# EMAIL_BACKEND to the SMTP backend explicitly when testing real delivery.
SMTP_EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEVELOPMENT_EMAIL_BACKEND = 'django.core.mail.backends.locmem.EmailBackend'
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    SMTP_EMAIL_BACKEND if DJANGO_ENV == 'production' else DEVELOPMENT_EMAIL_BACKEND,
).strip()
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com').strip()
try:
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
except ValueError as exc:
    raise ImproperlyConfigured('EMAIL_PORT must be an integer.') from exc
EMAIL_USE_TLS = _bool_env('EMAIL_USE_TLS', True)
EMAIL_USE_SSL = _bool_env('EMAIL_USE_SSL', False)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '').strip()
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'webmaster@localhost').strip()
try:
    EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '15'))
except ValueError as exc:
    raise ImproperlyConfigured('EMAIL_TIMEOUT must be an integer.') from exc

if EMAIL_USE_TLS and EMAIL_USE_SSL:
    raise ImproperlyConfigured('EMAIL_USE_TLS and EMAIL_USE_SSL cannot both be enabled.')

if EMAIL_BACKEND == SMTP_EMAIL_BACKEND:
    missing_email_settings = [
        name for name, value in {
            'EMAIL_HOST': EMAIL_HOST,
            'EMAIL_HOST_USER': EMAIL_HOST_USER,
            'EMAIL_HOST_PASSWORD': EMAIL_HOST_PASSWORD,
            'DEFAULT_FROM_EMAIL': DEFAULT_FROM_EMAIL,
        }.items() if not value
    ]
    if missing_email_settings:
        raise ImproperlyConfigured(
            'SMTP email is enabled but required settings are missing: '
            + ', '.join(missing_email_settings)
        )

# Google Cloud Speech-to-Text settings used by the reading assessment UI.
GOOGLE_STT_API_KEY = 'AIzaSyDPMgJX8t195Z9bfoID2gwlG5oPhBVK_tk'
GOOGLE_CLOUD_PROJECT_ID = 'project-2b0d295d-ee06-40a7-927'
GOOGLE_STT_LOCATION = 'us'
# Chirp 3 is used through Speech-to-Text V2 Recognize for short reading clips.
GOOGLE_STT_MODEL = 'chirp_3'
GOOGLE_STT_CREDENTIALS_FILE = BASE_DIR / 'google-stt-service-account.json'
PABASA_OVERRIDE_SECURITY_CODE = os.environ.get('PABASA_OVERRIDE_SECURITY_CODE', '')

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'pabasa-default-cache',
    }
}

# When a CSRF failure occurs, prefer a JSON response for AJAX requests so frontend can handle it.
CSRF_FAILURE_VIEW = 'pabasa_app.views.csrf_failure'
