"""
Django settings for pabasa_site project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c8tcixn4vam*#z1*^d+9x6ddm89ph_+z%5+jce14vgdr@#*y5t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

def _csv_env(name):
    value = os.environ.get(name, '')
    return [item.strip() for item in value.split(',') if item.strip()]


def _dedupe(items):
    seen = set()
    output = []
    for item in items:
        if item and item not in seen:
            seen.add(item)
            output.append(item)
    return output


ALLOWED_HOSTS = _dedupe(_csv_env('ALLOWED_HOSTS') + [
    'tupcpabasa.app',
    'www.tupcpabasa.app',
    'pabasa-workspace.onrender.com',
    '127.0.0.1',
    'localhost',
])

CSRF_TRUSTED_ORIGINS = _dedupe(_csv_env('CSRF_TRUSTED_ORIGINS') + [
    'https://tupcpabasa.app',
    'https://www.tupcpabasa.app',
    'https://pabasa-workspace.onrender.com',
])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "pabasa_app",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pabasa_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pabasa_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

if os.environ.get('DJANGO_ENV', '').lower() == 'production':
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True

# Email settings for Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'pabasa.tupc@gmail.com'
EMAIL_HOST_PASSWORD = 'sfsy zplk rmku bdxt'
DEFAULT_FROM_EMAIL = 'pabasa.tupc@gmail.com'

# Google Cloud Speech-to-Text settings used by the reading assessment UI.
GOOGLE_STT_API_KEY = 'AIzaSyD1NqLTpMSzmkAdFX6UpcuJ-y4bT9mrXbk'
GOOGLE_CLOUD_PROJECT_ID = 'direct-outlet-499701-p6'
GOOGLE_STT_LOCATION = 'us'
GOOGLE_STT_MODEL = 'chirp_3'
GOOGLE_STT_CREDENTIALS_FILE = BASE_DIR / 'google-stt-service-account.json'

# When a CSRF failure occurs, prefer a JSON response for AJAX requests so frontend can handle it.
CSRF_FAILURE_VIEW = 'pabasa_app.views.csrf_failure'
