# Generated by Django 6.0.3 on 2026-06-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingclass',
            name='grade_level',
            field=models.CharField(default='Grade 1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readingclass',
            name='section',
            field=models.CharField(default='Sampaguita', max_length=50),
            preserve_default=False,
        ),
    ]
