# Generated by Django 5.2.15 on 2026-09-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0001_current_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeDebugSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('unlock_all', models.BooleanField(default=False)),
            ],
        ),
    ]
