# Generated by Django 6.0.3 on 2026-06-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0002_readingclass_grade_level_readingclass_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingclass',
            name='subject',
            field=models.CharField(default='English', max_length=50),
            preserve_default=False,
        ),
    ]
