# Generated by Django 6.0.3 on 2026-06-12 07:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0008_assessment_content_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 6, 12, 15, 54, 49, 378798)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='pabasa_app.section'),
        ),
        migrations.AddField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='pabasa_app.assessment'),
        ),
        migrations.AddField(
            model_name='material',
            name='assigned_week',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
