# Generated by Django 5.2.15 on 2026-09-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0010_student_session_idle_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentactivityrecordingsubmission',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
