# Generated by Django 5.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0011_alter_studentactivityrecordingsubmission_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='publication_scope',
            field=models.CharField(
                choices=[('whole_class', 'Whole Class'), ('selected_students', 'Selected Students')],
                default='whole_class',
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name='MaterialStudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='pabasa_app.material')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_assignments', to='pabasa_app.user')),
            ],
            options={'db_table': 'material_student_assignments'},
        ),
        migrations.AddConstraint(
            model_name='materialstudentassignment',
            constraint=models.UniqueConstraint(fields=('material', 'student'), name='uniq_material_student_assignment'),
        ),
    ]
