# Generated by Django 6.0.3 on 2026-06-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0012_convert_assessments_to_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='assigned_sections',
            field=models.ManyToManyField(blank=True, related_name='assigned_materials', to='pabasa_app.section'),
        ),
        migrations.AddField(
            model_name='material',
            name='content_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='material',
            name='content_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='material',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('scheduled', 'Scheduled')], default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='material',
            name='title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='material',
            name='prompt_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
