# Generated by Django 6.0.3 on 2026-06-13 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0013_material_assigned_sections_material_content_json_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['section', 'created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='material',
            name='unique_section_item_order',
        ),
        migrations.RemoveField(
            model_name='material',
            name='audio_url',
        ),
        migrations.RemoveField(
            model_name='material',
            name='expected_answer',
        ),
        migrations.RemoveField(
            model_name='material',
            name='order_index',
        ),
    ]
