# Generated by Django 6.0.3 on 2026-06-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0016_user_archive_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('practice', 'Practice'), ('assessment', 'Assessment'), ('both', 'Both')], default='practice', max_length=20),
        ),
    ]
