# Generated by Django 6.0.3 on 2026-06-15 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0017_material_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('practice_type', models.CharField(choices=[('word', 'Word'), ('sentence', 'Sentence'), ('paragraph', 'Paragraph')], max_length=20)),
                ('difficulty_type', models.CharField(blank=True, max_length=50)),
                ('contents', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempts', models.JSONField(blank=True, default=list)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practices', to='pabasa_app.user')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practices', to='pabasa_app.section')),
            ],
            options={
                'db_table': 'practices',
                'ordering': ['-created_at'],
            },
        ),
    ]
