# Generated by Django 6.0.3 on 2026-06-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0018_create_practice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='grade_level',
        ),

        migrations.RemoveField(
            model_name='section',
            name='section',
        ),
    ]

