# Generated by Django 5.2.15 on 2026-10-03 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0018_term_scoped_student_activity_progress'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='storyreadingprogress',
            name='unique_legacy_story_reading_progress',
        ),
        migrations.RemoveConstraint(
            model_name='storyreadingprogress',
            name='unique_enrollment_story_reading_progress',
        ),
        migrations.RemoveConstraint(
            model_name='storyresponsesubmission',
            name='unique_story_response_student_material',
        ),
        migrations.AddField(
            model_name='storyreadingprogress',
            name='school_calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='story_reading_progress', to='pabasa_app.schoolcalendar'),
        ),
        migrations.AddField(
            model_name='storyreadingprogress',
            name='term',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')], null=True),
        ),
        migrations.AddField(
            model_name='storyresponsesubmission',
            name='school_calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='story_response_submissions', to='pabasa_app.schoolcalendar'),
        ),
        migrations.AddField(
            model_name='storyresponsesubmission',
            name='term',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')], null=True),
        ),
        migrations.AddConstraint(
            model_name='storyreadingprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('enrollment__isnull', True), ('school_calendar__isnull', True), ('term__isnull', True)), fields=('student', 'material'), name='unique_legacy_story_reading_progress'),
        ),
        migrations.AddConstraint(
            model_name='storyreadingprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('enrollment__isnull', False), ('school_calendar__isnull', False), ('term__isnull', False)), fields=('enrollment', 'school_calendar', 'term', 'material'), name='unique_scoped_story_reading_progress'),
        ),
        migrations.AddConstraint(
            model_name='storyresponsesubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('school_calendar__isnull', True), ('term__isnull', True)), fields=('student', 'material'), name='unique_legacy_story_response_student_material'),
        ),
        migrations.AddConstraint(
            model_name='storyresponsesubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('school_calendar__isnull', False), ('term__isnull', False)), fields=('student', 'material', 'school_calendar', 'term'), name='unique_scoped_story_response_student_material'),
        ),
    ]
