# Generated by Django 5.2.15 on 2026-10-03 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0019_remove_storyreadingprogress_unique_legacy_story_reading_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='supplementary_school_calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplementary_assessment_results', to='pabasa_app.schoolcalendar'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='supplementary_term',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')], null=True),
        ),
    ]
