# Generated by Django 5.2.15 on 2026-10-03 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0020_assessment_supplementary_school_calendar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentrequest',
            name='official_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_requests', to='pabasa_app.material'),
        ),
        migrations.AddField(
            model_name='assessmentrequest',
            name='official_phase',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assessmentrequest',
            name='school_calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_requests', to='pabasa_app.schoolcalendar'),
        ),
        migrations.AddField(
            model_name='assessmentrequest',
            name='term',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
