# Generated by Django 5.2.15 on 2026-10-03 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0021_assessment_request_current_crla_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialstudentassignment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prescribedactivityaccesssettings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='SupplementaryMaterialPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_publications', to='pabasa_app.material')),
                ('school_calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplementary_publications', to='pabasa_app.schoolcalendar')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_publications', to='pabasa_app.section')),
            ],
            options={
                'db_table': 'supplementary_material_publications',
                'constraints': [models.UniqueConstraint(fields=('material', 'school_calendar', 'term', 'section'), name='uniq_supplementary_material_term_publication')],
            },
        ),
    ]
