# Generated by Django 6.0.3 on 2026-10-04 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0022_alter_materialstudentassignment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplementaryStudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_student_assignments', to='pabasa_app.enrollment')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='pabasa_app.supplementarymaterialpublication')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_student_assignments', to='pabasa_app.user')),
            ],
            options={
                'db_table': 'supplementary_student_assignments',
                'constraints': [models.UniqueConstraint(fields=('publication', 'student'), name='uniq_supplementary_publication_student_assignment')],
            },
        ),
    ]
