# Generated by Django 6.0.3 on 2026-07-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0029_remove_practice_content_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='content',
        ),
        migrations.AlterField(
            model_name='practice',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('scheduled', 'Scheduled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('principal', 'Principal'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=20),
        ),
    ]
