# Generated by Django 6.0.3 on 2026-07-01 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0027_material_source_type'),
        ('pabasa_app', '0030_remove_assessment_content_alter_practice_status_and_more'),
    ]

    operations = [
    ]
