# Generated by Django 6.0.3 on 2026-07-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0032_assessment_attempts_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='attempt_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='attempts',
            new_name='attempt_history',
        ),
    ]
