# Generated by Django 6.0.3 on 2026-07-02 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0033_alter_assessment_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='attempt_history',
        ),
        migrations.AddField(
            model_name='assessment',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='attempt_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='assessment',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assessment',
            name='attempt_status',
            field=models.CharField(default='started', max_length=20),
        ),
        migrations.AddField(
            model_name='assessment',
            name='classification',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='assessment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='crla_classification',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='assessment',
            name='device_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='assessment',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='fluency_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='items_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='mic_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='needs_manual_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='pronunciation_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='assessment',
            name='source_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempt_rows', to='pabasa_app.assessment'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='speech_recognition_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='stars_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_attempt_rows', to='pabasa_app.user'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='time_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='total_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='transcript',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='assessment',
            name='word_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='wpm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
