# Generated by Django 6.0.3 on 2026-07-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0040_live_assessment_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('word', 'Word'), ('vowel', 'Vowel'), ('sentence', 'Sentence'), ('paragraph', 'Paragraph')], max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='item_type',
            field=models.CharField(choices=[('word', 'Word'), ('vowel', 'Vowel'), ('sentence', 'Sentence'), ('paragraph', 'Paragraph')], max_length=20),
        ),
    ]
