# Generated by Django 6.0.3 on 2026-07-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0041_alter_assessment_assessment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveassessmentsession',
            name='activity_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='liveassessmentsession',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveassessmentsession',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveassessmentsession',
            name='student_states',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='liveassessmentsession',
            name='timing_mode',
            field=models.CharField(choices=[('none', 'None'), ('duration', 'Duration'), ('deadline', 'Deadline')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='liveassessmentsession',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('started', 'Started'), ('paused', 'Paused'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
    ]
