# Generated by Django 6.0.3 on 2026-07-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0043_assessment_correct_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveassessmentsession',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('countdown', 'Countdown'), ('started', 'Started'), ('paused', 'Paused'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='liveassessmentsession',
            name='timing_mode',
            field=models.CharField(choices=[('none', 'No Limit'), ('duration', 'Duration')], default='none', max_length=20),
        ),
    ]
