# Generated by Django 6.0.3 on 2026-08-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0047_material_student_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='animal_avatar',
            field=models.CharField(blank=True, default='cat', max_length=20),
        ),
    ]
