# Generated by Codex on 2026-08-05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0048_user_animal_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='assessment_set',
            field=models.CharField(blank=True, default='', max_length=20, choices=[('crla', 'CRLA Assessment Set'), ('word', 'Word Assessment Set'), ('sentence', 'Sentence Assessment Set'), ('paragraph', 'Paragraph Assessment Set')]),
        ),
        migrations.CreateModel(
            name='AssessmentWindowSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='assessment_window_active', max_length=50, unique=True)),
                ('active_window', models.CharField(choices=[('bosy', 'Beginning of School Year'), ('mosy', 'Middle of School Year'), ('eosy', 'End of School Year')], default='bosy', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_window_updates', to='pabasa_app.user')),
            ],
            options={
                'db_table': 'assessment_window_settings',
            },
        ),
    ]
