# Generated by Django 6.0.3 on 2026-08-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0054_official_reading_assessments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentwindowsetting',
            name='active_window',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('archived', 'Archived'), ('scheduled', 'Scheduled')], default='published', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('scheduled', 'Scheduled')], default='published', max_length=20),
        ),
        migrations.AlterField(
            model_name='practice',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('archived', 'Archived'), ('scheduled', 'Scheduled')], default='draft', max_length=20),
        ),
    ]
