# Generated by Django 6.0.3 on 2026-08-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0056_calendar_event_title_and_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='term',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')], default=1),
        ),
    ]
