# Generated by Django 6.0.3 on 2026-08-22 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0063_material_assigned_weeks_template_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('start_of_classes', 'Start of Classes'), ('end_of_classes', 'End of Classes'), ('school_opening', 'Opening Block'), ('school_closing', 'End-of-Term Block'), ('pre_assessment', 'Pre-Assessment Week'), ('post_assessment', 'Post-Assessment Week'), ('holiday', 'Holiday'), ('examination', 'Examination Week'), ('other', 'Other Activity')], max_length=30),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='term',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3'), (4, 'Term 4')], default=1),
        ),
        migrations.AlterField(
            model_name='officialreadingintegrityauthorization',
            name='authorized_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_integrity_authorizations', to='pabasa_app.user'),
        ),
        migrations.AlterField(
            model_name='officialreadingintegrityoverriderequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_override_requests', to='pabasa_app.user'),
        ),
        migrations.AlterField(
            model_name='officialreadingintegrityoverriderequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_official_override_requests', to='pabasa_app.user'),
        ),
        migrations.AlterField(
            model_name='officialreadingoverridesecuritylockout',
            name='reviewer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='official_override_security_lockout', to='pabasa_app.user'),
        ),
        migrations.AlterField(
            model_name='schoolcalendar',
            name='current_term',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3'), (4, 'Term 4')]),
        ),
        migrations.DeleteModel(
            name='AssessmentWindowSetting',
        ),
    ]
