# Generated by Django 6.0.3 on 2026-08-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0080_merge_0079_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='system_assessment_key',
            field=models.CharField(blank=True, choices=[('', 'Teacher Owned'), ('bosy_crla_pretest', 'BoSY CRLA Pre-Test'), ('midline_crla_midtest', 'Midline CRLA Mid-Test'), ('eosy_crla_posttest', 'EoSY CRLA Post-Test')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('start_of_classes', 'Start of Classes'), ('end_of_classes', 'End of Classes'), ('school_opening', 'Opening Block'), ('school_closing', 'End-of-Term Block'), ('pre_assessment', 'Pre-Assessment Week'), ('midline_assessment', 'Midline Assessment Week'), ('post_assessment', 'Post-Assessment Week'), ('holiday', 'Holiday'), ('examination', 'Examination Week'), ('other', 'Other Activity')], max_length=30),
        ),
    ]
