# Generated by Django 6.0.3 on 2026-09-02 16:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0096_liveassessmentsession_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryResponseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, default='')),
                ('response_text', models.TextField(blank=True, default='')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='story_responses/%Y/%m/%d/')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Grade'), ('graded', 'Graded')], default='pending', max_length=20)),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_response_submissions', to='pabasa_app.enrollment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_story_response_submissions', to='pabasa_app.user')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_response_submissions', to='pabasa_app.material')),
                ('story_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_response_source_submissions', to='pabasa_app.material')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_response_submissions', to='pabasa_app.user')),
            ],
            options={
                'db_table': 'story_response_submissions',
                'constraints': [models.UniqueConstraint(fields=('student', 'material'), name='unique_story_response_student_material')],
            },
        ),
    ]
