# Generated by Django 6.0.3 on 2026-09-04 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0100_backfill_assessment_week_enabled_default'),
        ('pabasa_app', '0102_alter_accountstatushistory_id_alter_assessment_id_and_more'),
    ]

    operations = [
    ]
