# Generated by Django 5.0.7 on 2026-09-08

import django.db.models.deletion
from django.db import migrations, models
import pabasa_app.system_clock


class Migration(migrations.Migration):

    dependencies = [
        ("pabasa_app", "0109_liveassessmentsession_batch_loaded_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassCrlaFinalization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("finalized_at", models.DateTimeField(default=pabasa_app.system_clock.now)),
                ("finalized_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="crla_finalizations", to="pabasa_app.user")),
                ("material", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="class_finalizations", to="pabasa_app.material")),
                ("section", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="crla_finalizations", to="pabasa_app.section")),
            ],
        ),
        migrations.AddConstraint(
            model_name="classcrlafinalization",
            constraint=models.UniqueConstraint(fields=("section", "material"), name="unique_section_crla_finalization"),
        ),
    ]
