# Generated by Django 6.0.3 on 2026-09-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0111_dropped_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstatushistory',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending_archive', 'Pending Archive'), ('dropped', 'Dropped'), ('archived', 'Archived')], max_length=20),
        ),
    ]
