# Generated by Django 6.0.3 on 2026-09-08 20:30

from django.db import migrations, models


def remove_incomplete_admin_practice_materials(apps, schema_editor):
    Material = apps.get_model('pabasa_app', 'Material')
    candidates = Material.objects.filter(
        type='practice',
        section__isnull=True,
        teacher__isnull=True,
        is_system_owned=True,
        source_type='shared',
        content_json__mode__in=['free', 'color', 'hunt'],
        content_json__difficulty__in=['easy', 'medium', 'hard'],
        content_json__level__in=['level_1', 'level_2', 'level_3', 'level_4', 'level_5'],
    )
    incomplete_ids = [
        material.pk
        for material in candidates.only('pk', 'content_text')
        if not (material.content_text or '').strip()
    ]
    if incomplete_ids:
        Material.objects.filter(pk__in=incomplete_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0112_alter_accountstatushistory_status'),
    ]

    operations = [
        migrations.RunPython(remove_incomplete_admin_practice_materials, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(models.F('language'), models.F('content_json__mode'), models.F('content_json__difficulty'), models.F('content_json__level'), condition=models.Q(('is_system_owned', True), ('section__isnull', True), ('source_type', 'shared'), ('teacher__isnull', True), ('type', 'practice'), models.Q(('content_text', ''), _negated=True)), name='uniq_valid_admin_practice_slot'),
        ),
    ]
