# Generated by Django 6.0.3 on 2026-09-08 20:30

from django.db import migrations, models


def remove_incomplete_admin_practice_materials(apps, schema_editor):
    # Keep the historical callable without deleting records during migration.
    # Empty content is already excluded from the constraint and occupied slots.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pabasa_app', '0112_alter_accountstatushistory_status'),
    ]

    operations = [
        migrations.RunPython(remove_incomplete_admin_practice_materials, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(models.F('language'), models.F('content_json__mode'), models.F('content_json__difficulty'), models.F('content_json__level'), condition=models.Q(('is_system_owned', True), ('section__isnull', True), ('source_type', 'shared'), ('teacher__isnull', True), ('type', 'practice'), models.Q(('content_text', ''), _negated=True)), name='uniq_valid_admin_practice_slot'),
        ),
    ]
